### ISSUE TITLE
Make sure validation errors from schxslt are parsed properly

### ISSUE THREAD

**Issue by halfbyte** [halfbyte/ruby-secretariat#5]
Thanks to @SubandiK, we have proper detection of actual validation errors (Thanks for reporting #1 and providing a fix in #3) but looking at the output in the provided test case it seems to me like an error is reported in multiple lines and it would be good if we could parse these lines into actual `ValidationError` objects.

If someone wants to give this a go, please go ahead. I am not in the best position right now to spend a lot of time on this, but I will eventually get to it if nobody will pick this up.

**Comment by SubandiK** [comment]
Thanks for parsing the errors!
